from selenium import webdriver
import time
from selenium.webdriver.common.keys import Keys
driver= webdriver.Firefox()
driver.get("https://www.google.com/")
search = driver.find_element('xpath','//*[@id="APjFqb"]')
search.send_keys("Githup")
search.send_keys(Keys.ENTER)
time.sleep(10)
githubopen=driver.find_element('xpath',"/html/body/div[5]/div/div[11]/div[1]/div[2]/div[2]/div/div/div[1]/div/div/div/div/div/div/div/div[1]/div/span/a").click()
githubopen = driver.find_element('xpath','//*[@id="user_email"]')
githubopen.send_keys("Habibullahbalti44@gmail.com")
time.sleep(5)
githubopen.send_keys(Keys.ENTER)
time.sleep(5)
githubopen=driver.find_element('xpath','/html/body/div[1]/div[1]/header/div/div/div/a').click()
time.sleep(4)
githubopen = driver.find_element('xpath','//*[@id="login_field"]')
githubopen.send_keys("habibullah46")
time.sleep(4)
githubopen = driver.find_element('xpath','//*[@id="password"]')
githubopen.send_keys("habibkhalqi1234")
time.sleep(4)
githubopen=driver.find_element('xpath','/html/body/div[1]/div[3]/main/div/div[4]/form/div/input[13]').click()
githubopen = driver.find_element('xpath','/html/body/div[1]/div[1]/header/div/div[2]/div[3]/deferred-side-panel/include-fragment/user-drawer-side-panel').click()
githubopen = driver.find_element('xpath','/html/body/div[1]/div[1]/header/div/div[2]/div[3]/deferred-side-panel/include-fragment/user-drawer-side-panel/dialog-helper/dialog/scrollable-region/div/div/nav/nav-list/ul/li[3]/a/span[2]').click()
githubopen = driver.find_element('xpath','//*[@id="repositories-tab"]').click()